// Code generated by "stringer -type=columnFlag"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[hidden-1]
	_ = x[key-2]
	_ = x[writable-16]
	_ = x[nullable-32]
	_ = x[identity-64]
}

const (
	_columnFlag_name_0 = "hiddenkey"
	_columnFlag_name_1 = "writable"
	_columnFlag_name_2 = "nullable"
	_columnFlag_name_3 = "identity"
)

var (
	_columnFlag_index_0 = [...]uint8{0, 6, 9}
)

func (i columnFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _columnFlag_name_0[_columnFlag_index_0[i]:_columnFlag_index_0[i+1]]
	case i == 16:
		return _columnFlag_name_1
	case i == 32:
		return _columnFlag_name_2
	case i == 64:
		return _columnFlag_name_3
	default:
		return "columnFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
