// Code generated by "stringer -type=packetType"; DO NOT EDIT.

package tds

import "strconv"

const (
	_packetType_name_0 = "nonePacketqueryPacketloginPacketrpcPacketreplyPacket"
	_packetType_name_1 = "cancelPacketbulkPacket"
	_packetType_name_2 = "normalPacket"
)

var (
	_packetType_index_0 = [...]uint8{0, 10, 21, 32, 41, 52}
	_packetType_index_1 = [...]uint8{0, 12, 22}
)

func (i packetType) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _packetType_name_0[_packetType_index_0[i]:_packetType_index_0[i+1]]
	case 6 <= i && i <= 7:
		i -= 6
		return _packetType_name_1[_packetType_index_1[i]:_packetType_index_1[i+1]]
	case i == 15:
		return _packetType_name_2
	default:
		return "packetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
