// Code generated by "stringer -type=token"; DO NOT EDIT.

package tds

import "strconv"

const _token_name = "NoneCapabilityReqCapabilityResParamFmt2LanguageOrderBy2WideColumnFmtDynamic2MsgLogoutReturnStatusCurCloseCurDeleteCurFetchCurFmtCurOpenCurDeclareTableNameColumnInfoOptionCmdCmpRowNameCmpRowFmtOrderByInfoLoginAckControlRowCmpRowParamCapabilitiesEnvChangesqlMessageDbRPCDynamicParamFmtAuthColumnFmtDoneDoneProcDoneInProc"

var _token_map = map[token]string{
	0:   _token_name[0:4],
	1:   _token_name[4:17],
	2:   _token_name[17:30],
	32:  _token_name[30:39],
	33:  _token_name[39:47],
	34:  _token_name[47:55],
	97:  _token_name[55:68],
	98:  _token_name[68:76],
	101: _token_name[76:79],
	113: _token_name[79:85],
	121: _token_name[85:97],
	128: _token_name[97:105],
	129: _token_name[105:114],
	130: _token_name[114:122],
	131: _token_name[122:128],
	132: _token_name[128:135],
	134: _token_name[135:145],
	164: _token_name[145:154],
	165: _token_name[154:164],
	166: _token_name[164:173],
	167: _token_name[173:183],
	168: _token_name[183:192],
	169: _token_name[192:199],
	171: _token_name[199:203],
	173: _token_name[203:211],
	174: _token_name[211:218],
	209: _token_name[218:221],
	211: _token_name[221:227],
	215: _token_name[227:232],
	226: _token_name[232:244],
	227: _token_name[244:253],
	229: _token_name[253:263],
	230: _token_name[263:268],
	231: _token_name[268:275],
	236: _token_name[275:283],
	237: _token_name[283:287],
	238: _token_name[287:296],
	253: _token_name[296:300],
	254: _token_name[300:308],
	255: _token_name[308:318],
}

func (i token) String() string {
	if str, ok := _token_map[i]; ok {
		return str
	}
	return "token(" + strconv.FormatInt(int64(i), 10) + ")"
}
