// Code generated by "stringer -type=token"; DO NOT EDIT.

package tds

import "strconv"

const _token_name = "noneTokencapabilityReqTokencapabilityResTokenparamFmt2ToeknlanguageTokenorderBy2TokenwideColumnFmtTokendynamic2TokenmsgTokenlogoutTokenreturnStatusTokencurCloseTokencurDeleteTokencurFetchTokencurFmtTokencurOpenTokencurDeclareTokentableNameTokencolumnInfoTokenoptionCmdTokencmpRowNameTokencmpRowFmtTokenorderByTokeninfoTokenloginAckTokencontrolTokenrowTokencmpRowTokenparamTokencapabilitiesTokenenvChangeTokensqlMessageTokendbRPCTokendynamicTokenparamFmtTokenauthTokencolumnFmtTokendoneTokendoneProcTokendoneInProcToken"

var _token_map = map[token]string{
	0:   _token_name[0:9],
	1:   _token_name[9:27],
	2:   _token_name[27:45],
	32:  _token_name[45:59],
	33:  _token_name[59:72],
	34:  _token_name[72:85],
	97:  _token_name[85:103],
	98:  _token_name[103:116],
	101: _token_name[116:124],
	113: _token_name[124:135],
	121: _token_name[135:152],
	128: _token_name[152:165],
	129: _token_name[165:179],
	130: _token_name[179:192],
	131: _token_name[192:203],
	132: _token_name[203:215],
	134: _token_name[215:230],
	164: _token_name[230:244],
	165: _token_name[244:259],
	166: _token_name[259:273],
	167: _token_name[273:288],
	168: _token_name[288:302],
	169: _token_name[302:314],
	171: _token_name[314:323],
	173: _token_name[323:336],
	174: _token_name[336:348],
	209: _token_name[348:356],
	211: _token_name[356:367],
	215: _token_name[367:377],
	226: _token_name[377:394],
	227: _token_name[394:408],
	229: _token_name[408:423],
	230: _token_name[423:433],
	231: _token_name[433:445],
	236: _token_name[445:458],
	237: _token_name[458:467],
	238: _token_name[467:481],
	253: _token_name[481:490],
	254: _token_name[490:503],
	255: _token_name[503:518],
}

func (i token) String() string {
	if str, ok := _token_map[i]; ok {
		return str
	}
	return "token(" + strconv.FormatInt(int64(i), 10) + ")"
}
