// Code generated by "stringer -type=PacketType"; DO NOT EDIT.

package netlib

import "strconv"

const (
	_PacketType_name_0 = "NoneQueryLoginRPCReply"
	_PacketType_name_1 = "CancelBulk"
	_PacketType_name_2 = "Normal"
)

var (
	_PacketType_index_0 = [...]uint8{0, 4, 9, 14, 17, 22}
	_PacketType_index_1 = [...]uint8{0, 6, 10}
)

func (i PacketType) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _PacketType_name_0[_PacketType_index_0[i]:_PacketType_index_0[i+1]]
	case 6 <= i && i <= 7:
		i -= 6
		return _PacketType_name_1[_PacketType_index_1[i]:_PacketType_index_1[i+1]]
	case i == 15:
		return _PacketType_name_2
	default:
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
